# You'll probably have to do xhost +"local:docker@" on the host first
services:
  pydev_hw:
    user: "${UID}:${GID}" 
    image: bradmears/pydev_hw:latest
    hostname: pydev_hw
    build: .
    privileged: true
    working_dir: ${HOME}
    environment:
      - DISPLAY=${DISPLAY}
      - USER=${USER}
    volumes:
      - ${HOME}:${HOME}
      - /dev/serial/by-id/usb-0403_6014-if00-port0:/dev/FT232H
      #- /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    network_mode: host
